[package]
name = "serialport"
version = "3.1.1-alpha.0"
authors = ["Bryant Mairs <bryant@mai.rs>"]
categories = ["hardware-support"]
keywords = ["serial", "hardware", "system", "RS232"]
license = "MPL-2.0"
readme = "README.md"
repository = "https://gitlab.com/susurrus/serialport-rs"
description = "A cross-platform low-level serial port library"
documentation = "https://docs.rs/serialport/*/serialport"

[badges]
appveyor = { repository = "Susurrus/serialport-rs", service = "gitlab" }
gitlab = { repository = "susurrus/serialport-rs" }
travis-ci = { repository = "Susurrus/serialport-rs" }

[dev-dependencies]
argparse = "0.2"

[target."cfg(unix)".dependencies]
nix = "0.11"
bitflags = "1.0"

[target."cfg(windows)".dependencies]
regex = "1.0"

[target."cfg(windows)".dependencies.winapi]
version = "0.3.6"
features = ["cguid", "commapi", "errhandlingapi", "fileapi", "guiddef", "handleapi", "minwinbase",
            "minwindef", "ntdef", "setupapi", "winbase", "winerror", "winnt"]

[target.'cfg(target_os = "macos")'.dependencies]
IOKit-sys = "0.1"
mach = "0.2"
CoreFoundation-sys = "0.1.3"
